term.clear()
term.setCursorPos(1,1)
term.write('username: ')
user = read()
print()
term.write('password: ')
pass = read('*')
print()
term.write('side[top,bottom,left,right,front,back]: ')
side = read()
print()
term.write('keyFile[disk/]:')
local path = read()
disk.setLabel(side,user)
local tbl = {authentication = pass}
local file = fs.open('disk/'..path,'w')
file.write(textutils.serialize(tbl))
file.close()
disk.eject(side)